In [ ]:
import tensorflow as tf
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [ ]:
const_tensor = tf.constant([[1,2,3], [4,5,6]])
var_tensor = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float32)
bool_tensor = tf.Variable([True, False, True], dtype=tf.bool)

In [ ]:
# print(const_tensor.shape, "\n", var_tensor.shape)
print(const_tensor)
print(var_tensor)
print(bool_tensor)

#### Exercise :Declare a tensor of shape (2, 2, 2, 2) with random numbers from a normal distribution whose mean and standard deviation are both 1.

In [ ]:
arr = np.random.randn(2,2,2,2)  #randn function gives mean = 0 & std.dev = 1

In [ ]:
print("shape: ", arr.shape)
print("values: ", arr)

In [ ]:
#if we want to achieve mean = 1 and std.dev = 1

arr = (arr * 1) + 1
print(arr)

In [ ]:
arr_tf = tf.constant(arr)
print(arr_tf)

In [ ]:
print(type(arr_tf.numpy()))

#### using tensorflow

In [ ]:
arr_tf2 = tf.random.normal(shape=(2,2,2,2), mean=1, stddev=1)
print(arr_tf2.numpy())

### Commom mathematical operations

In [ ]:
x = tf.Variable([list(range(5))] * 5)
y = tf.Variable([list(range(5, 10))] * 5)
print("x: ", x)
print("y: ", y)

In [ ]:
""" Simple mathmatical operations"""

z = x + y
print(z)

w = x * y
print(w)

v = x / y
print(v)

#### Linear algebra functions

In [ ]:
y = tf.Variable([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])  #shape (5,3)
z = tf.transpose(y)
print("Before transpose: ", y)
print("After transpose: ", z)

In [ ]:
tf.pow(y, 2)

In [ ]:
tensor1 = tf.random.uniform(shape=(2,2), minval=1, maxval=20, dtype=tf.int32)

tensor_sq = tensor1 * tensor1
print(tensor1)
print(tensor_sq)

### Linear Algebra with Tensorflow

In [20]:
x = tf.Variable([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24]])
y = tf.Variable([[0,1,2], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])

z = tf.linalg.matmul(x, y)
print("z: ", z)

z:  tf.Tensor(
[[ 100  110  120]
 [ 270  305  340]
 [ 440  500  560]
 [ 610  695  780]
 [ 780  890 1000]], shape=(5, 3), dtype=int32)


#### Note: if tf.linalg.matmul raises expection when the size of matrix elements are imcompatible for matrix multiplication

In [23]:
# Matrix Inverse

try:
    x = tf.Variable([[2,3], [2,2]])
    xinv = tf.linalg.inv(x)
    print("inverse of x: ", xinv)
except Exception as e:
    print("Exception raised when the size of matrix elements are imcompatible\n", str(e))    

Exception raised when the size of matrix elements are imcompatible
 Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]


#### Note that, for inverse matrix operation, we need to specify the type for the elements as "float" types

In [22]:
x = tf.Variable([[2,3], [2,2]], dtype=tf.float32)
xinv = tf.linalg.inv(x)
print("inverse of x: ", xinv)

inverse of x:  tf.Tensor(
[[-1.   1.5]
 [ 1.  -1. ]], shape=(2, 2), dtype=float32)


In [29]:
# Solving Linear equations
# Eq: x + y + z + w     = 13
# Eq: 2x + 3y − w       = −1
# Eq: −3x + 4y + z + 2w = 10
# Eq: x + 2y − z + w    = 1

coeff = tf.Variable([[1, 1, 1, 1], [2, 3, 0, -1], [-3, 4, 1, 2], [1, 2, -1, 1]], 
                    dtype = tf.float32)

y = tf.Variable([[13], [-1], [10], [1]], dtype=tf.float32)

inv_coeff = tf.linalg.inv(coeff)
print('inverse of coeff: ', inv_coeff)

#solving x, y, z, w
x = tf.matmul(inv_coeff, y)

print("x: ", x)
#print("y: ", x * coeff)

inverse of coeff:  tf.Tensor(
[[ 2.77777791e-01  5.55555224e-02 -1.66666672e-01  1.11111104e-01]
 [-7.40740746e-02  1.85185164e-01  1.11111104e-01  3.70370336e-02]
 [ 4.62962925e-01  9.25926119e-02  5.55555634e-02 -4.81481493e-01]
 [ 3.33333343e-01 -3.33333343e-01 -9.93410776e-09  3.33333343e-01]], shape=(4, 4), dtype=float32)
x:  tf.Tensor(
[[ 2.0000000e+00]
 [-1.0058284e-07]
 [ 5.9999995e+00]
 [ 5.0000005e+00]], shape=(4, 1), dtype=float32)


In [60]:
### Question 1
W = tf.Variable([[0.5], [1.0], [-1.2]])
x = tf.Variable([[0.2, 1,  0.5]])
b = tf.Variable([[0.01]])

val = tf.add(tf.matmul(x, W), b)

sig = tf.sigmoid(val)
print(sig.numpy())

[[0.62480646]]
